### ISSUE TITLE
It take a while to show up three html elments <div>class="row-container editor-container" </div> on https://extendsclass.com/

### ISSUE THREAD

**Issue by APIPLM** [cyrilbois/cyrilex#4]
Not sure this is a place to raise this issue. But it is the repo, where it has related to the test tools on https://extendsclass.com/.
In my side. It takes about more than two mins to show up the three  `editors-container` <div> elements. I have not found out what it block those elements on the webpage. Would you have some suggestion? Thanks in advance.

**Comment by cyrilbois** [comment]
Two mins ... it is very long! It is strange for this page.
The site is hosted in France, maybe some scripts take time to load (a problem with the cdn that I use?).

**Comment by APIPLM** [comment]
Thanks. you mean that switch to a proxy, which can access cdn fast?  But I checked that the network info in the debug mode. It has three scripts need to be loaded again as i refresh the page.  They are from https://fundingchoicesmessages.google.com.

**Comment by APIPLM** [comment]
Yes. As I download the source (HTML/CSS, Javascript scripts)to my local site , and remove the loading those scripts in the HTML from https://fundingchoicesmessages.google.com/, it works. I mean the blocked three `editor-container` divs in the page show up immediately, and I can go further to run my test case on the page. Thanks.
