### ISSUE TITLE
Javascript engine only (other engines commented)

### ISSUE THREAD

**Issue by sallecta** [cyrilbois/cyrilex#5]
In demo site there are more engines (https://extendsclass.com/regex-tester.html), but in current source java-script engine available only.
I also noticed that other engines commented in index.html.
When trying to uncomment other engines a lot of 'self is undefined' errors occurs in developer's console.

**Comment by cyrilbois** [comment]
Hello,
I have not had time to clean my code yet, on my site it is hosted between several hostings, a part under docker, cgi etc.
So I have not been able to open source it yet.

**Comment by sallecta** [comment]
Hello,
Could you upload 'pcre.php', so I can try to enable it.

**Comment by cyrilbois** [comment]
Hello,
Sorry, I just saw your reply now...
I've uploaded the file to the "backend" folder (same for Python/Ruby).
